server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://47.91.45.226:3306/votesys?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#        url: jdbc:mysql://127.0.0.1:3306/votesys?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.hundsun.votesystem.model